// Generated by Wrangler on Fri Aug 02 2024 16:56:18 GMT+0530 (India Standard Time)
// by running `wrangler types --env-interface CloudflareBindings`

export interface CloudflareBindings {
	whatsapp_hono: KVNamespace;
	ACCESS_TOKEN: "EAAQLINQB4B0BO0lXAIV7frX65Q0bxzQnJOsonPzht8nIuBZC5XgjkTbrm7sSKUvMPMv79NxVNGpO8YQERgv3tZBNJ5Sjj0ZArZBAIhTAtRcHSG9qNd4p8aYZArvuIc2h3mf0FQzFTl7373G9Xk7Bb71Vpu4D3xkVrpDHwqr3NontstloTpLwQheHZC6RiLbg9ZBh8ZCfNcxwm8abn3ilGZCEZD";
	SUPABASE_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZsY2hzbmpnd2toYnF5Y2Rtcnl3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MTMyOTEzMzAsImV4cCI6MjAyODg2NzMzMH0.W07pp5qJIne-bsgORuQoXuJERpVFce2w0nRtfDRFouY";
	MY_DB: D1Database;
	AI: Ai;
}
